### ISSUE TITLE
캠퍼스 소개 카드 뉴스 컨텐츠 기획 - 5월 2일

### ISSUE THREAD

**Issue by yeongunheo** [woowacourse/Branding#1]
- 주제 선정 (잠실, 선릉)
  - 건물 내외부 사진
  - 주변 맛집
  - 위치
    - 지름길
    - 지하철 환승팁
  - 컨셉 소개
    - 잠실은 자연, 스포츠
    - 선릉은 우주
  - 시설 이용 규칙
    - 사용시간
    - 예약
    - 식사
  - 내부 공간 소개
    - 강의실
    - 방 이름, 의미
    - 회의실 사용법(찜꽁)
    - 사용 목적 
      - 페어 프로그래밍
  - 잠실 한강뷰, 선릉 테헤란로뷰

**Comment by kang-hyungu** [comment]
- 고민할 부분
  - 어떤 순서로 배열할까?
  - 어떤 주제를 그룹핑 할까?
  - 각 주제 당 어떤 키워드를 넣을 것인가
  - 몇 부작으로 할까?
  - 기획한 내용 다음주(5월 2일) 공유

**Comment by tonic523** [comment]
- 6.28 캠퍼스 소개 카드뉴스 회의
https://docs.google.com/presentation/d/16zUOvWx9Rg4bNB3z5kiceUFNbyIHIickQ7tZogTZwkg/edit#slide=id.g1264f7faef5_0_26
