### ISSUE TITLE
[테코톡] 루나의 테코톡 초안을 제작한다.

### ISSUE THREAD

**Issue by chawani** [woowacourse/Branding#129]

**Comment by chawani** [comment]
https://www.miricanvas.com/v/11bsn65

**Comment by byhhh2** [comment]
<img width="400" alt="스크린샷 2022-08-16 오후 1 58 08" src="https://user-images.githubusercontent.com/52737532/184801096-4f62df66-ffa4-4f51-8202-f467fa36142b.png">

이 부분은 글씨 크기 조금 조절해서 한 줄에 작성해도 되지 않을까요? ㅎㅎ 개인적인 생각입니당.

**Comment by awesomeo184** [comment]
👍
