### ISSUE TITLE
[테코톡] 코이의 테코톡 초안을 제작한다.

### ISSUE THREAD

**Issue by jin7969** [woowacourse/Branding#133]

**Comment by jin7969** [comment]
https://www.miricanvas.com/v/115yqnc

**Comment by tonic523** [comment]
<img width="448" alt="image" src="https://user-images.githubusercontent.com/59171113/184800443-108b9a10-4b14-46b0-8e5e-a16b0183357a.png">

이 부분이 조금 비어보이는데 혹시 해당 설명에 대한 예시나 사진이 있을까요?

**Comment by byhhh2** [comment]
<img width="500" alt="스크린샷 2022-08-16 오후 1 54 32" src="https://user-images.githubusercontent.com/52737532/184800694-20480469-62b6-4d64-af23-26cde6a4f72f.png">

이 부분만 특정 문장이 기울임꼴로 되어있는데 특정한 이유가 있을까요?!

**Comment by awesomeo184** [comment]
👍
