### ISSUE TITLE
[문화] 브랜딩 근로팀 소개에 대한 초안을 제작한다.

### ISSUE THREAD

**Issue by awesomeo184** [woowacourse/Branding#136]

**Comment by awesomeo184** [comment]
https://www.miricanvas.com/v/11br2md

3페이지, 4페이지는 1안과 2안이 있습니다.

3, 4페이지가 1안, 5, 6페이지가 2안입니다. 어떤게 더 나을지 의견 부탁드립니다!

**Comment by tonic523** [comment]
저는 2안이 더 맘에 듭니다!

**Comment by byhhh2** [comment]
전 2안이 조금 더 귀여운 것 같네요 !! :) 

추가적으로 

<img width="300" alt="스크린샷 2022-08-16 오후 1 51 14" src="https://user-images.githubusercontent.com/52737532/184800323-dfb38440-a54b-4259-ad64-a5afdd1e67f7.png">

이 부분은 질문 내용을 좀 수정하는 것이 좋을 것 같습니다! 약간 친구와 대화하는 느낌이 좀 더 큰 것 같아서요 ㅎㅎ
`"브랜딩 근로, 직접 해보니 어떠신가요?"` 이 정도는 어떨까요?

**Comment by Gyuchool** [comment]
저도 2안이 더 좋습니다!

**Comment by chawani** [comment]
2안이 좀 더 좋네요:)

**Comment by jin7969** [comment]
저도 2안이요 ㅎㅎ
사진은 브랜딩 근로 사람으로 하면 어떨까요??

**Comment by awesomeo184** [comment]
2안 적용, 질문 수정 완료했습니다. 사진은 추가적으로 업로드하겠습니다!
