### ISSUE TITLE
[테코톡] 범고래, 소주캉의 테코톡 초안을 제작한다.

### ISSUE THREAD

**Issue by Gyuchool** [woowacourse/Branding#138]

**Comment by Gyuchool** [comment]
https://www.miricanvas.com/v/11bqlj2

**Comment by byhhh2** [comment]
<img width="400" alt="스크린샷 2022-08-16 오후 1 44 45" src="https://user-images.githubusercontent.com/52737532/184799606-b6a89bd8-5906-4ba1-b41d-eb3a0fe35b56.png">

다른 장들은 제목과 내용의 글씨 크기가 차이가 보이게 다른 것 같은데 이 부분은 거의 같네요?! 다른 이유가 있을까요?

**Comment by awesomeo184** [comment]
👍

**Comment by Gyuchool** [comment]
수정하겠습니다!
