### ISSUE TITLE
[테코톡] 유세지의 테코톡 초안을 제작한다.

### ISSUE THREAD

**Issue by injoon2019** [woowacourse/Branding#148]

**Comment by injoon2019** [comment]
https://www.miricanvas.com/v/11brs37

**Comment by Gyuchool** [comment]
![image](https://user-images.githubusercontent.com/60054318/184797201-6c027211-e752-4f0a-b4e9-57719b4b9bdf.png)
`에서는`으로 붙이면 더 좋을 것 같습니다!

**Comment by byhhh2** [comment]
<img width="400" alt="스크린샷 2022-08-16 오후 1 41 32" src="https://user-images.githubusercontent.com/52737532/184799288-52f8253b-3c70-4c40-bc89-95bbeb2e4e65.png">

글이 조금 빽빽하게 모여있다는는 생각이 들어서요! 행간을 조금 주면 어떨까요?

**Comment by awesomeo184** [comment]
<img width="794" alt="image" src="https://user-images.githubusercontent.com/63030569/184800843-808b3025-c341-4216-b9dc-a8fedbf81ff9.png">
여기도 무비랑 같은 의견입니다!
