### ISSUE TITLE
[문화] 페어프로그래밍에 대한 내용 기획한다.

### ISSUE THREAD

**Issue by Wonmi91** [woowacourse/Branding#15]

**Comment by byhhh2** [comment]
2조 무비, 알파

**Comment by byhhh2** [comment]
[문화 / 페어 프로그래밍 기획 PPT](https://docs.google.com/presentation/d/1uTkOlTeTNtO67CSUxv4yUvBj3eeFvM0FV_1HrQaQShY/edit#slide=id.p)
