### ISSUE TITLE
[문화] 테코톡에 대한 내용 기획한다.

### ISSUE THREAD

**Issue by Wonmi91** [woowacourse/Branding#16]

**Comment by yeongunheo** [comment]
1조 아키, 마루, 밧드

**Comment by chawani** [comment]
**0. 썸네일**
- 우아한테크코스 테코톡을 소개합니다

**1. 테코톡이 무엇인가, 어떤 주제들로 하는가**
- '테코톡'이란  우아한테크코스 과정을 진행하며 수강생들이 동료들과 학습한 내용을 공유하고 이야기하는 시간입니다. 크루들과 공유하고 싶은 주제라면 무엇이든 자유롭게 선택해 진행할 수 있습니다.
 
**2. 테코톡은 왜 하는가**
- 현장에서 필요한 말하기 능력 향상을 목적으로 하며, 서로가 성장하기 위해 지식을 나누고 대화하며 생각해보는 시간을 가질 수 있습니다. 테코톡은 자기주도적인 성장을 지향하는 우아한테크코스의 문화 중 하나입니다.

**3. 테코톡 하는 모습**
- (모여서 발표하는 사진)

**4. 테코톡을 준비하는 과정(인터뷰 같은 느낌)**
- 테코톡 준비(준비 기간, 집중한 부분)
- 테코톡 소감(고충, 소감)

**5. 테코톡이 어디에 업로드 되는지, 테코톡에 대한 유투브 반응(댓글, 조회수, 좋아요 수)**
- 테코톡은 우아한Tech 유튜브에 업로드됩니다. 
- 조회수, 좋아요 수 캡쳐 사진 삽입
- 댓글은 직접 따와서 타이핑

**6. 마지막 페이지**
- 매주 업로드되는 테코톡을 기대해주세요
