### ISSUE TITLE
[문화] 스모디팀 소개 최종본을 제작한다.

### ISSUE THREAD

**Issue by awesomeo184** [woowacourse/Branding#174]

**Comment by awesomeo184** [comment]
https://www.miricanvas.com/v/11dglmh

**Comment by bcc0830** [comment]
![1662262098918](https://user-images.githubusercontent.com/50986686/188528009-870728b6-b387-47ff-adc6-36c97c426944.jpg)
![1662262100391](https://user-images.githubusercontent.com/50986686/188528018-65646fd8-381b-4af6-8170-97c09ccaa422.jpg)
![1662262101784](https://user-images.githubusercontent.com/50986686/188528020-df41e406-ef46-473f-8ff0-00cfa7ae0a03.jpg)
![1662262103062](https://user-images.githubusercontent.com/50986686/188528023-d02db280-8583-4634-b861-d5a309286c9b.jpg)
