### ISSUE TITLE
[문화] 티타임팀 소개 최종본을 제작한다.

### ISSUE THREAD

**Issue by yeongunheo** [woowacourse/Branding#177]

**Comment by chawani** [comment]
https://www.miricanvas.com/v/11dgrkr

**Comment by yeongunheo** [comment]
## 수정사항
- 티타임 팀원들 사진들 넣기
- 왼쪽 하단 팀원에 [티타임 마루] => [마루]
- 제목 선 삐져나온 것 정리하기
