### ISSUE TITLE
[테코톡] 레오의 테코톡 최종본을 제작한다.

### ISSUE THREAD

**Issue by yeongunheo** [woowacourse/Branding#182]
### 피드백 
- 8장에서 문장마다 개행 추가

**Comment by yeongunheo** [comment]
https://www.miricanvas.com/v/11dzijc

**Comment by jin7969** [comment]
<img width="732" alt="스크린샷 2022-09-13 오후 2 53 35" src="https://user-images.githubusercontent.com/82227098/189820529-f71f6a61-fb12-4bcc-beda-f11d88a0d697.png">

밑에 글자에서 강조부분을 표시하면 좋을거 같아요!
