### ISSUE TITLE
[테코톡] 블링의 테코톡 최종본을 제작한다.

### ISSUE THREAD

**Issue by chawani** [woowacourse/Branding#184]

**Comment by chawani** [comment]
https://www.miricanvas.com/v/11dz66k

**Comment by Gyuchool** [comment]
![image](https://user-images.githubusercontent.com/60054318/189821899-7dd30436-8ab3-4867-a5d8-af2e02d0f4f5.png)
"웹서비스를 " 붙이는 것도 좋아보입니다.
