### ISSUE TITLE
[테코톡] 이스트의 테코톡 최종본을 제작한다.

### ISSUE THREAD

**Issue by Gyuchool** [woowacourse/Branding#188]

**Comment by Gyuchool** [comment]
https://www.miricanvas.com/v/11dwmyt

**Comment by awesomeo184** [comment]
👍

**Comment by jin7969** [comment]
<img width="978" alt="스크린샷 2022-09-13 오후 2 56 58" src="https://user-images.githubusercontent.com/82227098/189821092-7c736ca8-0ae4-4cd4-87cd-209c1a3ec72f.png">

이 부분을 전체적으로 위로 올리면 어떨까요?

**Comment by byhhh2** [comment]
할-까 붙여주세요!!
