### ISSUE TITLE
[테코톡] 라쿤의 테코톡 최종본을 제작한다.

### ISSUE THREAD

**Issue by injoon2019** [woowacourse/Branding#198]

**Comment by injoon2019** [comment]
https://www.miricanvas.com/v/11ehm57

**Comment by jin7969** [comment]
<img width="762" alt="스크린샷 2022-09-19 오후 3 02 16" src="https://user-images.githubusercontent.com/82227098/190957656-e83614d8-f13e-4e17-b568-0ddf692f2caa.png">

밑에 부분 조금 추가하면 좋을거 같아요

**Comment by kamwoo** [comment]
밑에 있는 글들의 위치를 살짝 올려도 좋을거 같아요!
