### ISSUE TITLE
우테코 소개 카드 뉴스 컨텐츠 기획 - 5월 2일

### ISSUE THREAD

**Issue by injoon2019** [woowacourse/Branding#2]
- 어떤 컨텐츠를 넣을까?
  - 모집 시기(10월)
    - 프리코스 소개
  - 미션 중심의 교육
  - 교육 기간
  - 교육 과정
    - 페어 프로그래밍
    - 코드리뷰
    - 프로젝트
    - 말하기
    - 글쓰기
  - 배민다움 > 우테코 컨텐츠
  - 우테코 사이트 내용 요약
  - 학습 주제
    - 자바, 스프링
    - 자바스크립트, 리액트
    - TDD
    - 리팩터링
  - 우테코가 추구하는 개발자의 모습

**Comment by kang-hyungu** [comment]
- 고민할 부분
  - 어떤 순서로 배열할까?
  - 어떤 주제를 그룹핑 할까?
  - 각 주제 당 어떤 키워드를 넣을 것인가
  - 몇 부작으로 할까?
  - 기획한 내용 다음주(5월 2일) 공유

**Comment by awesomeo184** [comment]
- 2부작
  - 교육 관련 내용
    - 우테코가 뭐하는 곳인가요? ( 사이트 랜딩 페이지 요약)
    - 어떤 목적의 교육인가?
    - 교육과정
  - 모집 관련 내용
    - 모집 시기(10월)
    - 코딩테스트(언어 상관없음)
    - 프리코스 (자바, 자바스크립트)
    - 교육 기간(10개월, 자바&스프링, 자바스크립트&리액트)

**Comment by byhhh2** [comment]
[기획 PPT](https://docs.google.com/presentation/d/1LxA4rxiiHGaMIXNyfrsKCXuOHZK3iTMjUtEkx2uDZZc/edit?usp=sharing)

**Comment by kang-hyungu** [comment]
프리코스도 기간이 바뀔 수 있어서 기간은 빼고 어떤 내용으로 진행하는지만 소개해주세요!

**Comment by awesomeo184** [comment]
@kang-hyungu 저희 2부작으로 진행하기로 했는데, 월요일 회의 때, 1.2부작 모두 준비해야할까요 아니면 1부작만 준비해서 가도 될까요?

**Comment by awesomeo184** [comment]
[2부 기획 PPT](https://docs.google.com/presentation/d/1W8zIcxAkHRGSvdsfccpZnrxR_ZCN24uHyLTKgKmKq3c/edit#slide=id.p)
