### ISSUE TITLE
[테코톡] 민초의 테코톡 최종본을 제작한다.

### ISSUE THREAD

**Issue by kamwoo** [woowacourse/Branding#204]

**Comment by kamwoo** [comment]
[미리캔버스 링크](https://www.miricanvas.com/login?redirect=%2Fdesign%2F11ejplm)

**Comment by injoon2019** [comment]
마지막 장에 유튜브 검색창에 세로로 정렬 하면 더 좋을 것 같아요!

**Comment by yeongunheo** [comment]
<img width="690" alt="image" src="https://user-images.githubusercontent.com/52141636/190957941-8190c73a-f096-4a16-9157-1c9218dbf452.png">

REST가 약어이니까 강조표시를 해도 괜찮을 것 같아요!
