### ISSUE TITLE
[테코톡] 기론과 리버의 테코톡 최종본을 제작한다

### ISSUE THREAD

**Issue by bcc0830** [woowacourse/Branding#211]

**Comment by bcc0830** [comment]
https://www.miricanvas.com/v/11eii18

**Comment by yeongunheo** [comment]
밑에 3줄을 2줄로 합쳐도 될 것 같아요!
5줄이니까 가독성이 저하된다는 느낌을 받았아요ㅎ

<img width="910" alt="image" src="https://user-images.githubusercontent.com/52141636/192201082-dc72d2fa-fd58-408d-9980-f7f1a2be8ad7.png">
