### ISSUE TITLE
[테코톡] 비녀의 테코톡 최종본을 제작한다.

### ISSUE THREAD

**Issue by kamwoo** [woowacourse/Branding#214]

**Comment by kamwoo** [comment]
[링크](https://www.miricanvas.com/v/11f65ah)

**Comment by jin7969** [comment]
- 전체적으로 부분부분 글자 강조 색상 넣으면 좋을거 같아요
- 제목과 내용이 붙어있는거 같아 제목 글자 크기를 키우고 내용과 띄우면 좋을거 같아요

**Comment by byhhh2** [comment]
좋네요 👏

**Comment by awesomeo184** [comment]
👍
