### ISSUE TITLE
[테코톡] 파랑, 아키의 테코톡 최종본을 제작한다.

### ISSUE THREAD

**Issue by awesomeo184** [woowacourse/Branding#215]

**Comment by awesomeo184** [comment]
https://www.miricanvas.com/v/11f6uzh

**Comment by jin7969** [comment]
<img width="640" alt="스크린샷 2022-09-26 오후 1 23 40" src="https://user-images.githubusercontent.com/82227098/192193469-c76381ee-d10c-4b21-9cdd-76513af26bff.png">

- 마지막 문장도 위의 내용과 맞춰서 가운데 정렬하면 좋을거 같아요

**Comment by injoon2019** [comment]
마지막 장 유튜브 검색창 정렬 해주시면 좋을 것 같아요!

**Comment by byhhh2** [comment]
오,, 좋네요 😮

**Comment by yeongunheo** [comment]
마지막 문장을 좀 더 키워도 좋을 것 같아요!

<img width="906" alt="image" src="https://user-images.githubusercontent.com/52141636/192200873-c57957d6-febf-4f8e-adda-62dae8f9a5b4.png">

**Comment by chawani** [comment]
안이 올려주신 부분 화살표를 그냥 직선으로 내려도 될 것 같아요! 뭔가 채워넣으려다가 만듯한 느낌이 들어요
