### ISSUE TITLE
[테코톡] 에덴의 테코톡 최종본을 제작한다.

### ISSUE THREAD

**Issue by jin7969** [woowacourse/Branding#219]

**Comment by jin7969** [comment]
https://www.miricanvas.com/v/115yqnc

**Comment by injoon2019** [comment]
고생하셨습니다!👍

**Comment by byhhh2** [comment]
- IP 부분 다른 곳과 통일성 있게 대문자로 하는게 좋을 것 같아요 ㅎㅎ

<img width="293" alt="스크린샷 2022-09-26 오후 2 28 39" src="https://user-images.githubusercontent.com/52737532/192200170-66c9d1d8-e9f5-4f38-b1c9-c3717dcc2996.png">

좋네요 ~~

**Comment by yeongunheo** [comment]
이부분 맨 윗줄은 정의이고, 나머지는 설명인데
정의 부분을 인용문구 같은걸로 구분해보는건 어떨까요?

<img width="903" alt="image" src="https://user-images.githubusercontent.com/52141636/192200378-281603f1-2761-4e6f-9b47-fdf7c7e7475e.png">

**Comment by kamwoo** [comment]
- 제목 아래 사진과 설명 부분 전체를 세로 중간 맞춤 해도 좋을 것 같습니다.
- 목차 위치가 이전까지 컨벤션과 맞지 않아서 왼쪽으로 맞추면 좋겠습니다. 👍

**Comment by awesomeo184** [comment]
👍
