### ISSUE TITLE
[테코톡]토닉, 후디의 테코톡 최종본을 제작한다

### ISSUE THREAD

**Issue by Gyuchool** [woowacourse/Branding#221]

**Comment by Gyuchool** [comment]
https://www.miricanvas.com/v/11f0g0x

**Comment by tonic523** [comment]
- 예를 들어 쿠키와 세션, JWT 토큰 같은 주제에 대해서 색깔을 입히면 좋을 것 같아요!
- OAuth와 OpenId의 목적을 간단하게 한 줄이라도 있으면 좋을 것 같아요 ㅎㅎ

**Comment by jin7969** [comment]
전체적으로 글자 강조 표시(주황색) 하면 좋을 거 같아요!

**Comment by injoon2019** [comment]
`인터넷 환경의 인증과 인가` 부분 글들이 너무 붙어 있는 것 같아요!

**Comment by byhhh2** [comment]
- 거친 후 띄어쓰기 해주세요! (3번째 페이지) 
- 설명글 글씨 크기가 다른 것 같은데 제 개인적인 생각으로는 통일하는게 좋을 것 같아요 ㅎㅎ
 
<img width="634" alt="스크린샷 2022-09-26 오후 2 27 11" src="https://user-images.githubusercontent.com/52737532/192200020-5018f838-ce35-4629-b671-9a70893d3a90.png">

<img width="634" alt="스크린샷 2022-09-26 오후 2 27 21" src="https://user-images.githubusercontent.com/52737532/192200036-626a8b6e-bab3-4497-a399-41b22961b6f8.png">

**Comment by chawani** [comment]
강조를 좀 더 넣어도 좋을 것 같아요~!

**Comment by kamwoo** [comment]
목차 간격을 줄여도 좋을 것 같습니다. 👍
