### ISSUE TITLE
[테코톡] 시지프의 테코톡 최종본을 제작한다.

### ISSUE THREAD

**Issue by byhhh2** [woowacourse/Branding#229]

**Comment by byhhh2** [comment]
[초안](https://www.miricanvas.com/v/11fuciw)

**Comment by jin7969** [comment]
역시 무비!👍

**Comment by injoon2019** [comment]
![image](https://user-images.githubusercontent.com/46641538/193737363-f4bce6cf-f7ab-47d7-8e79-6e87821b113f.png)

이거 `예시` 의도된 것일까요? 의도된거면 놔둬도 될 것 같아요

**Comment by byhhh2** [comment]
넵 의도입니다!

**Comment by chawani** [comment]
👍

**Comment by Gyuchool** [comment]
👍
