### ISSUE TITLE
[테코톡] 온스타의 테코톡 최종본을 제작한다

### ISSUE THREAD

**Issue by awesomeo184** [woowacourse/Branding#230]

**Comment by awesomeo184** [comment]
https://www.miricanvas.com/v/11fw2l8

**Comment by byhhh2** [comment]
👏

**Comment by jin7969** [comment]
- 글자 크기를 조금 키우는거 어떨까요?? - 개인적인 생각입니다.
<img width="753" alt="스크린샷 2022-10-04 오전 11 09 58" src="https://user-images.githubusercontent.com/82227098/193719576-27192daa-baaf-49c9-9171-0a518db8df40.png">

**Comment by injoon2019** [comment]
![image](https://user-images.githubusercontent.com/46641538/193737013-03e16b87-bd63-4f61-a97a-c419f5b8ffee.png)
이거 배경 투명한 것 넣을 수 있을까요??

**Comment by byhhh2** [comment]
토르 의견에 동의합니다!

**Comment by awesomeo184** [comment]
에고; 저걸 못봤었네요. 투명 배경으로 수정했습니다 감사합니다

**Comment by chawani** [comment]
👍

**Comment by Gyuchool** [comment]
👍

**Comment by yeongunheo** [comment]
👍
