### ISSUE TITLE
[테코톡]라라, 제로의 테코톡 최종본을 제작한다.

### ISSUE THREAD

**Issue by tonic523** [woowacourse/Branding#231]

**Comment by tonic523** [comment]
[초안 링크](https://www.miricanvas.com/v/11fv62i)

**Comment by byhhh2** [comment]
👏

**Comment by jin7969** [comment]
👍

**Comment by injoon2019** [comment]
뒤에서 두번째 장 '사용'만 줄바꿈이 되는게 조금 어색한 것 같아요! 아예 붙이거나 조금 일찍 줄바꿈하는건 어떨까요?

**Comment by awesomeo184** [comment]
👍

**Comment by chawani** [comment]
👍

**Comment by Gyuchool** [comment]
![image](https://user-images.githubusercontent.com/60054318/193744680-46ee4f66-4a19-4012-85b0-46af605b670e.png)
Primary Key도 한 줄로 적을 수 있을것 같은데 가능하면 한 줄로 적으면 더 좋을 것 같기도 하네요

**Comment by yeongunheo** [comment]
👍
