### ISSUE TITLE
[테코톡] 썬의 테코톡 최종본을 제작한다

### ISSUE THREAD

**Issue by yeongunheo** [woowacourse/Branding#232]

**Comment by yeongunheo** [comment]
https://www.miricanvas.com/v/11fv2nt

**Comment by byhhh2** [comment]
- 글꼴이 두 종류가 혼합돼서 사용되는데 어떤 기준으로 바뀌는지 애매한 것 같아요! 
- 단어는 붙이면 좋을 것 같아요 ㅎㅎ! (만들 때마다)

<img width="636" alt="스크린샷 2022-10-04 오전 10 38 51" src="https://user-images.githubusercontent.com/52737532/193716070-9c94a8e5-2968-42ec-a216-faeea049f3e3.png">

수고하셨습니다 ! 👏

**Comment by jin7969** [comment]
역시 아키 👍

**Comment by awesomeo184** [comment]
<img width="765" alt="스크린샷 2022-10-04 오후 2 13 35" src="https://user-images.githubusercontent.com/63030569/193739738-346543b5-880e-4499-a6d5-ac2f9df17dc6.png">

스크린샷보다는 텍스트 직접 넣는게 낫지 않을까요?? 스크린샷이 더 나은 것 같으시면 반영 안하셔도 됩니다~

**Comment by Gyuchool** [comment]
👍

**Comment by chawani** [comment]
👍
