### ISSUE TITLE
[테코톡] 애쉬의 테코톡 최종본을 제작한다

### ISSUE THREAD

**Issue by bcc0830** [woowacourse/Branding#235]
[편하게 보기](https://www.miricanvas.com/v/11fwciz)

**Comment by jin7969** [comment]
전체적으로 글자 강조 표시가 있으면 좋을 거 같아요

**Comment by injoon2019** [comment]
https://www.miricanvas.com/v/11fwciz

**Comment by injoon2019** [comment]
글자색 강조가 있으면 더 좋을 것 같아요!

**Comment by awesomeo184** [comment]
<img width="824" alt="스크린샷 2022-10-04 오후 2 02 14" src="https://user-images.githubusercontent.com/63030569/193738406-7d063346-ae24-4d35-a038-dd880d413569.png">

관련 이미지 첨부할 수 있지 않을까요?

**Comment by awesomeo184** [comment]
<img width="756" alt="스크린샷 2022-10-04 오후 2 20 39" src="https://user-images.githubusercontent.com/63030569/193740539-1b908fa2-6a96-4a53-acd0-9f4c203bb5c6.png">
다리 잘린거 밑에 맞춰주면 좋을 것 같아요

**Comment by chawani** [comment]
👍

**Comment by yeongunheo** [comment]
👍
