### ISSUE TITLE
[테코톡] 위니의 테코톡 최종본을 제작한다

### ISSUE THREAD

**Issue by Gyuchool** [woowacourse/Branding#236]

**Comment by Gyuchool** [comment]
https://www.miricanvas.com/v/11fsszq

**Comment by byhhh2** [comment]
<img width="906" alt="스크린샷 2022-10-04 오전 10 30 30" src="https://user-images.githubusercontent.com/52737532/193715248-84169c05-41f3-4726-8242-a53d9dc6c8de.png">

요기도 짤막하게 설명이 있으면 좋을 것 같습니다!

**Comment by jin7969** [comment]
### 1. 설명글에서 좌우 간격이 있으면 좋을 거 같아요!
<img width="805" alt="스크린샷 2022-10-04 오전 11 04 04" src="https://user-images.githubusercontent.com/82227098/193718981-9fb2baf7-9f3a-4a7f-a40c-6873d64e1f34.png">

### 2. 화살표 크기를 조금 줄이고 왼쪽 사진을 가운데로 조금 옮기면 어떨까요?
<img width="799" alt="스크린샷 2022-10-04 오전 11 04 55" src="https://user-images.githubusercontent.com/82227098/193719063-c62c3591-89d4-4510-b394-89edb49d6911.png">

**Comment by awesomeo184** [comment]
전체적으로 이미지 화질이 좀 안좋은 것 같은데 사용된 이미지가 혹시 유튜브 스크린샷일까요??, 만약 스크린샷이면 원본 PPT 자료로 첨부하는게 좋을 것 같아요~  

---

위니 테코톡 내용이 덜 들어간것 같은데, 나머지 내용은 유튜브로 확인해달라는 페이지가 추가되면 좋을 것 같아요.

**Comment by chawani** [comment]
양옆 여백을 좀 더 주면 좋을 것 같아요~
