### ISSUE TITLE
[인터뷰] 왼손 인터뷰 최종본을 제작한다.

### ISSUE THREAD

**Issue by Gyuchool** [woowacourse/Branding#250]

**Comment by Gyuchool** [comment]
https://www.miricanvas.com/v/11gh5yj

**Comment by byhhh2** [comment]
좋네요! 👍
인터뷰 중간중간 왼손의 사진이 들어가면 귀여울 것 같아요!

**Comment by jin7969** [comment]
글자 정렬을 맞추면 좋을거 같아요 "답정너"에서 끊기는 느낌입니다.
<img width="755" alt="스크린샷 2022-10-11 오후 2 12 48" src="https://user-images.githubusercontent.com/82227098/195002464-1082afa7-4f31-4bc0-82a3-fc70a16ad69d.png">


중요하지 않을까 이 부분도요
<img width="709" alt="스크린샷 2022-10-11 오후 2 13 17" src="https://user-images.githubusercontent.com/82227098/195002473-f16545a3-ab5f-44ac-b899-1270b48501d1.png">

**Comment by awesomeo184** [comment]
<img width="816" alt="image" src="https://user-images.githubusercontent.com/63030569/195004019-b3259ab0-2c47-4471-88f3-7fec8aa60e6e.png">

문장이 조금 어색하게 느껴지네요. "오늘 소개해드릴 인터뷰 챌린지의 주인공은 왼손입니다 ..." 이런 식으로 수정해보는건 어떨까요?

**Comment by awesomeo184** [comment]
<img width="749" alt="image" src="https://user-images.githubusercontent.com/63030569/195004585-5d67c49d-3a31-427a-a4b1-9cd87f996ddc.png">

4번 이미지 마지막줄 간격 왼쪽으로 당기면 좋을 것 같습니다.

**Comment by chawani** [comment]
인터뷰 장면 캡쳐가 중간중간 들어가면 더 좋을 것 같고 줄바꿈도 자연스러워지면 더 좋을 거 같아요~

**Comment by awesomeo184** [comment]
<img width="516" alt="image" src="https://user-images.githubusercontent.com/63030569/195004882-bbb08fe2-6f09-414b-9024-0fc196a3f361.png">

"아직은 없다"  이 부분은 요약인가요? 왼손의 답변이랑 구분을 해주거나 아니면 없어도 될 것 같아요

**Comment by tonic523** [comment]
> <img alt="image" width="516" src="https://user-images.githubusercontent.com/63030569/195004882-bbb08fe2-6f09-414b-9024-0fc196a3f361.png">
> 
> "아직은 없다" 이 부분은 요약인가요? 왼손의 답변이랑 구분을 해주거나 아니면 없어도 될 것 같아요

저도 이 부분은 없어도 괜찮을 것 같아요!

**Comment by tonic523** [comment]
`Q5` 를 2번 하셨는데 연결되는 내용이라 의도하신건가요?
