### ISSUE TITLE
[문화] 레벨3 데모데이 최종본을 제작한다.

### ISSUE THREAD

**Issue by kamwoo** [woowacourse/Branding#258]

**Comment by kamwoo** [comment]
[미리캔버스 링크](https://www.miricanvas.com/login?redirect=%2Fdesign%2F11ghp2y)

**Comment by byhhh2** [comment]
오 👏 너무 예쁘네요!!! 
데모데이 설명 관련 글이 조금 더 추가되면 좋을 것 같습니다 🙂

**Comment by injoon2019** [comment]
오 템플릿 진짜 예쁘네요

**Comment by jin7969** [comment]
이모지를 넣는다던지, 글자 굵기를 크게 한다던지 조금 꾸미면 좋은거 같아요

<img width="568" alt="스크린샷 2022-10-11 오후 2 07 23" src="https://user-images.githubusercontent.com/82227098/195001798-a4ecef0b-75be-4ad9-b1e3-bd94f9050bac.png">

**Comment by awesomeo184** [comment]
> 이모지를 넣는다던지, 글자 굵기를 크게 한다던지 조금 꾸미면 좋은거 같아요
> 
> <img alt="스크린샷 2022-10-11 오후 2 07 23" width="568" src="https://user-images.githubusercontent.com/82227098/195001798-a4ecef0b-75be-4ad9-b1e3-bd94f9050bac.png">

- "크루들에게 사건들과 팀문화..." 라고 되어있는데, 그냥 "사건들"이라고 하면 제대로 전달이 안될 것 같아요~
- 데모데이 관련한 설명이 좀 더 있으면 좋을 것 같습니다

**Comment by tonic523** [comment]
데모데이 관련 설명이 있으면 더 이해하기 좋을 것 같네요!

**Comment by chawani** [comment]
내용을 좀 더 보충하고, 글자 크기를 좀 더 키우면 좋을 것 같아요~

**Comment by bcc0830** [comment]
저도 같은 의견입니다!

**Comment by byhhh2** [comment]
사건들 => 에피소드?
