### ISSUE TITLE
[테코톡] 잉, 페퍼 테코톡 최종본을 제작한다.

### ISSUE THREAD

**Issue by tonic523** [woowacourse/Branding#266]
[링크](https://www.miricanvas.com/v/11h12s9)

**Comment by yeongunheo** [comment]
내용이 좋네요 👍 

마지막 장에 잉 페퍼 사진의 비율을 맞추면 좋을 것 같아요!

<img width="908" alt="image" src="https://user-images.githubusercontent.com/52141636/196096592-b1ee0a13-62fc-45c0-9d06-f5a0913bcbe7.png">

**Comment by chawani** [comment]
<img width="757" alt="스크린샷 2022-10-17 오후 2 44 05" src="https://user-images.githubusercontent.com/60432062/196098130-860ee2db-b58e-4f61-b040-fcf64923328a.png">
'PEPPER'가 코드 상에 없어서 무슨 말인지 모를 것 같아요!

<img width="755" alt="스크린샷 2022-10-17 오후 2 46 15" src="https://user-images.githubusercontent.com/60432062/196098788-ed526656-0d36-4176-ad00-4fed532da64f.png">
올바르게 엔티티~ 이 부분 가운데 정렬이 안된 것 같아요!

<img width="754" alt="스크린샷 2022-10-17 오후 2 46 46" src="https://user-images.githubusercontent.com/60432062/196098919-1fc97d84-b0e7-44ca-8476-fc2eff7d3caa.png">
JPQL 대문자로 통일하는 건 어떨까요? 그리고 x 동그라미 이모지의 의미가 뭔지 잘 모를거같아요~

**Comment by jin7969** [comment]
사진에 그림자를 추가하면 좋을거 같아요

**Comment by byhhh2** [comment]
고생하셨습니다 👏

<img width="723" alt="스크린샷 2022-10-17 오후 2 59 50" src="https://user-images.githubusercontent.com/52737532/196100247-e12ced19-51a4-4c9d-89a8-a2c8f320ff2b.png">

정렬이 조금 안맞네용 ㅎㅎ
