### ISSUE TITLE
[문화]FAQ 최종본을 제작한다.

### ISSUE THREAD

**Issue by Gyuchool** [woowacourse/Branding#268]

**Comment by Gyuchool** [comment]
https://www.miricanvas.com/v/113rp6n

**Comment by yeongunheo** [comment]
강조하는 글자의 색이 좀 더 눈에 띄는 색이면 좋을 것 같습니다!

<img width="600" alt="image" src="https://user-images.githubusercontent.com/52141636/196095853-ab8ced60-c5d1-4522-977f-ce011b73409e.png">

**Comment by awesomeo184** [comment]
<img width="832" alt="image" src="https://user-images.githubusercontent.com/63030569/196096934-f78f18f3-3561-4a41-ac59-36d581f6734f.png">

"자세한 내용은~" 부분 자간을 좀 더 키워도 될 것 같아요.

"우아한테크코스" 랑 "끗"을 정렬을 맞추거나 아니면 아얘 빼도 괜찮을 것 같아요.

**Comment by chawani** [comment]
제목 글자 크기가 너무 작은 것 같아요! 좀 더 키우면 좋을 것 같습니다
그리고 배경 색이 너무 진하다보니 글자 강조가 잘 안되는 느낌이에요🥲

**Comment by jin7969** [comment]
너무 글만 있는거 같아요. 조금 꾸며주면 좋을거 같아요

**Comment by byhhh2** [comment]
수고하셨습니다!

- 마침표 찍어주세요!
<img width="600" alt="스크린샷 2022-10-17 오후 2 56 37" src="https://user-images.githubusercontent.com/52737532/196099790-362567e1-9eca-4f6c-880a-c65c8ed2afc5.png">

- 제목이 제일 작은 느낌?!
<img width="270" alt="스크린샷 2022-10-17 오후 2 57 14" src="https://user-images.githubusercontent.com/52737532/196099860-8541ff60-0b19-4280-b3f3-1c6180057f88.png">
