### ISSUE TITLE
[문화] 마지막 데모데이 홍보 최종본을 제작한다.

### ISSUE THREAD

**Issue by chawani** [woowacourse/Branding#269]

**Comment by chawani** [comment]
https://www.miricanvas.com/v/11h14si

**Comment by awesomeo184** [comment]
👍 👍

**Comment by injoon2019** [comment]
👍 구글폼 링크 나중에 따로 글에 적어주시면 좋을 것 같아요!

**Comment by jin7969** [comment]
👍👍👍

- "게더타운"을  게더타운 #4358dc 색상으로 하면 어떨까요? 
<img width="558" alt="스크린샷 2022-10-17 오후 2 42 49" src="https://user-images.githubusercontent.com/82227098/196097987-58152f2d-8897-43c9-9862-c3436db63370.png">
- 4기 크루들이 열심히 개발하고 있는 사진을 올리면 어떨까요?
<img width="750" alt="스크린샷 2022-10-17 오후 2 42 40" src="https://user-images.githubusercontent.com/82227098/196098001-6fb265f1-6484-4d84-874a-172d262fb39d.png">

**Comment by Gyuchool** [comment]
![image](https://user-images.githubusercontent.com/60054318/196099338-62d7a71f-20c4-4c8e-ba0b-ffb060267f00.png)
저희 7월부터 프로젝트 시작했던거 같아요

**Comment by byhhh2** [comment]
오오 할로윈 테마 👏👏 넘 좋네요 >_<

<img width="600" alt="스크린샷 2022-10-17 오후 2 54 08" src="https://user-images.githubusercontent.com/52737532/196099468-27d9af29-b73c-4694-821c-a94cced8a83c.png">

`외부 사람들`보다는 `외부분들`이 나을 것 같아요!

<img width="600" alt="스크린샷 2022-10-17 오후 2 54 52" src="https://user-images.githubusercontent.com/52737532/196099562-9e4353c1-0729-44b9-9853-a25ce8989b32.png">

폼 주소가 진짜 어렵네요 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 댓글에 주소를 달던가 해야겠네용 🙂

**Comment by chawani** [comment]
- 우테코에 관심있는 누구나 and 관심있는 누구나 참관 가능하다
- 마지막장 대강의실 모습?
- 우주 할로윈 컨셉?
