### ISSUE TITLE
[문화] 5기 지원 관련 게시물 초안을 제작한다.

### ISSUE THREAD

**Issue by byhhh2** [woowacourse/Branding#270]

**Comment by byhhh2** [comment]
[초안](https://www.miricanvas.com/v/11gzs0k)

**Comment by yeongunheo** [comment]
깔끔하고 너무 좋네요 👍 
마지막 코치 QnA때 사진이 있으면 더 좋을 것 같아요!

**Comment by awesomeo184** [comment]
👍 👍

**Comment by jin7969** [comment]
와우 너무 잘하셨네요!! 역시 👍
- 코치 사진 있으면 좋을거 같아요.

- 숫자 기호를 기본 숫자로 하면 어떨까요
<img width="654" alt="스크린샷 2022-10-17 오후 2 28 57" src="https://user-images.githubusercontent.com/82227098/196096605-6162b324-29df-43c1-8851-c72491abcd00.png">

- 문장이 이어지는게 아니라서 숫자 또는 기호를 다는건 어떨까요?
<img width="668" alt="스크린샷 2022-10-17 오후 2 31 00" src="https://user-images.githubusercontent.com/82227098/196096636-155fdb99-d463-45a3-99e2-97b726d37140.png">

**Comment by chawani** [comment]
글자가 작은 부분들을 조금씩만 더 키워도 좋을 것 같아요!👍

**Comment by byhhh2** [comment]
백엔드, 프론트엔트 이모지 바꿔주세요!
