### ISSUE TITLE
[문화] 달록팀 최종본을 제작한다.

### ISSUE THREAD

**Issue by tonic523** [woowacourse/Branding#280]
[링크](https://www.miricanvas.com/design/11hie85)

**Comment by awesomeo184** [comment]
![image](https://user-images.githubusercontent.com/63030569/197450107-245742ab-0342-4196-a8de-dfce9a9c8a77.png)

그냥 `사진들`이라고 하는 것보다는 `달록의 기록`이라든가 하는 식으로 이름을 붙여줘도 좋을 것 같아요~

나머지는 너무 좋습니다~

**Comment by jin7969** [comment]
어썸오 말에 동의 합니다!

- 달력이 기록을 공유할때?  무슨 의미인지 잘 모르겠어요
<img width="751" alt="스크린샷 2022-10-24 오후 2 08 21" src="https://user-images.githubusercontent.com/82227098/197452555-2e6410de-9ccd-4b94-83f8-6d69fb248553.png">

**Comment by awesomeo184** [comment]
> 어썸오 말에 동의 합니다!
> 
> * 달력이 기록을 공유할때?  무슨 의미인지 잘 모르겠어요
> 
> <img alt="스크린샷 2022-10-24 오후 2 08 21" width="751" src="https://user-images.githubusercontent.com/82227098/197452555-2e6410de-9ccd-4b94-83f8-6d69fb248553.png">

이거 아마 달록팀이 쓰는 부제일거에요
