### ISSUE TITLE
[테코톡] 칙촉의 테코톡 최종본을 제작한다.

### ISSUE THREAD

**Issue by yeongunheo** [woowacourse/Branding#282]

**Comment by yeongunheo** [comment]
https://www.miricanvas.com/v/11hsgzj

**Comment by tonic523** [comment]
<img width="714" alt="image" src="https://user-images.githubusercontent.com/59171113/197447596-2e0e0ef2-b055-4188-a077-f2b2b8884d07.png">
TCP 동작과정 밑에 소제목으로 `소캣 생성`을 하면 어떨까요? 다음 페이지도 같은 형식으로 하면 좋을 것 같아요.

**Comment by tonic523** [comment]
<img width="514" alt="image" src="https://user-images.githubusercontent.com/59171113/197447704-61ef5f42-36bb-4454-afa0-c43e84f13302.png">
글씨 크기를 조금 줄여서 말풍선과 여백을 두면 좋을 것 같아요

**Comment by awesomeo184** [comment]
저도 토닉이 말씀해주신 부분 말고는 다 좋은 것 같습니다. 👍

**Comment by jin7969** [comment]
- 화살표 색상을 주황색으로 하면 어떨까요?
<img width="598" alt="스크린샷 2022-10-24 오후 2 02 22" src="https://user-images.githubusercontent.com/82227098/197451989-5304e552-170a-4da9-a010-760cac96cfea.png">

- 를, 을  맞추면 좋겠어요
<img width="846" alt="스크린샷 2022-10-24 오후 2 02 54" src="https://user-images.githubusercontent.com/82227098/197452003-85314a1a-47f3-4ef9-a72d-7c83915f56c3.png">

**Comment by tonic523** [comment]
Handshake 대소문자 통일!

**Comment by yeongunheo** [comment]
HandShake로 모두 통일했습니다!
