### ISSUE TITLE
[테코톡] 자스민, 병민 part2 테코톡 최종본을 제작한다.

### ISSUE THREAD

**Issue by kamwoo** [woowacourse/Branding#289]

**Comment by kamwoo** [comment]
[링크](https://www.miricanvas.com/v/11hrb0b)

**Comment by yeongunheo** [comment]
import와 하다/하지않다 사이를 모두 띄우거나 붙이면 좋을 것 같아요!
<img width="902" alt="image" src="https://user-images.githubusercontent.com/52141636/197456364-405486c2-248f-445c-b6aa-4096507abc66.png">


tree shaking을 모두 대문자 or 소문자로 통일하면 좋을 것 같아요!
<img width="899" alt="image" src="https://user-images.githubusercontent.com/52141636/197456278-8c6845ec-d0e6-4d1b-8777-f8d328d1d180.png">
