### ISSUE TITLE
[문화] 프롤로그 소개에 대한 초안을 제작한다.

### ISSUE THREAD

**Issue by byhhh2** [woowacourse/Branding#29]

**Comment by byhhh2** [comment]
- 템플릿 정하기 
- 내용 선정하기 
  - 프롤로그란 무엇인가?
  - 프롤로그의 존재 의미와 장점
  - 프롤로그 기능 소개 
    - 뱃지
    - 역량
    - 인기있는 학습로그
    - 리포트
  - 프롤로그 게시물 하나를 선정해 예시로 보여주기 
  - 프롤로그 개발팀 인터뷰 
- 일정
  - 내용 : ~ 7월 5일 화요일 밤12시까지
  - 디자인 : 수요일 ~ 7월 8일 금요일 밤12시까지
  - 검수 : 일요일 7월 10일 밤 11시 

- 내용 : 카테고리에 대한 내용 준비하기
- 디자인 : 템플릿 정하고 + 준비한 내용 디자인하기 
- 검수 : 디자인과 내용 검수

**Comment by byhhh2** [comment]
[프롤로그 소개 초안에 들어갈 내용](https://docs.google.com/presentation/d/1VmhQZYH0f-UHPMjZQGMEGnJiUyf7j6ckA1l6UX8NqHo/edit?usp=sharing)

**Comment by byhhh2** [comment]
### 수정된 내용

- 프롤로그란 무엇인가요?
  - 학습로그를 작성하는 이유는 무엇인가요?
- 프롤로그는 이런식으로 활용될 수 있어요.
  - 학습로그 작성
  - 작성된 학습로그를 통한 말하기 활동
  - 프롤로그 리포트 : 학습 셀크 체크
- 프롤로그 TIP 1 - 학습로그 작성 TIP
- 프롤로그 TIP 2 - 프롤로그를 즐길 수 있는 TIP
  - 인기있는 학습로그
  - 뱃지

**Comment by chawani** [comment]
## 카드뉴스 초안
![001](https://user-images.githubusercontent.com/60432062/178185483-cb70ab42-82d7-46e2-8a93-55830a9d84f3.png)
![002](https://user-images.githubusercontent.com/60432062/178185495-30db30e9-7533-42ab-9412-3f042cbb7fd3.png)
![003](https://user-images.githubusercontent.com/60432062/178185505-89e480d5-a379-4d17-982c-3f39738a39c1.png)
![004](https://user-images.githubusercontent.com/60432062/178185509-d3b351ca-4920-4f6b-8ace-820a0e9baff2.png)
![005](https://user-images.githubusercontent.com/60432062/178185514-305ad648-0c96-486c-8b58-285bc3ab5278.png)
![006](https://user-images.githubusercontent.com/60432062/178185516-607d0fab-e3e1-4b88-af26-e0f922b2ebbb.png)
![007](https://user-images.githubusercontent.com/60432062/178185521-cc5a1097-7da9-4e25-aee2-6234e467f7c7.png)
![008](https://user-images.githubusercontent.com/60432062/178185530-e6f44e6d-2ec7-4166-8797-9912289bdeb4.png)
![009](https://user-images.githubusercontent.com/60432062/178185536-591dcd84-6cc3-470f-90ec-93b882221968.png)

**Comment by chawani** [comment]
무비 : 6 - 10
마루 : 1 - 5
