### ISSUE TITLE
[테코톡] 엘리의 테코톡 최종본을 제작한다.

### ISSUE THREAD

**Issue by tonic523** [woowacourse/Branding#291]

**Comment by tonic523** [comment]
[링크](https://www.miricanvas.com/v/11igfv5)

**Comment by Gyuchool** [comment]
사진만 있는 곳은 사진 크기 키워도 좋을 것 같아요! 아니면 글씨 조금 추가해도 좋아보여요

**Comment by jin7969** [comment]
마지막 크루 사진 위로 올리면 좋을거 같아요
