### ISSUE TITLE
[테코톡]아스피의 테코톡 최종본을 제작한다

### ISSUE THREAD

**Issue by Gyuchool** [woowacourse/Branding#296]

**Comment by Gyuchool** [comment]
https://www.miricanvas.com/v/11iei5z

**Comment by tonic523** [comment]
<img width="623" alt="image" src="https://user-images.githubusercontent.com/59171113/199166345-ca6f6b82-cd37-4a5b-b602-ccb3371fe0b7.png">

이 내용은 텍스트로 작성해도 괜찮을 것 같아요!

**Comment by awesomeo184** [comment]
👍

**Comment by tonic523** [comment]
👍

**Comment by byhhh2** [comment]
여기 부분에서 개념과 방식이 분간이 잘 안되네요! 

<img width="500" alt="스크린샷 2022-11-01 오후 2 47 29" src="https://user-images.githubusercontent.com/52737532/199167351-539fd45d-6cbc-4192-a58e-65cfddcc6a72.png">
