### ISSUE TITLE
우테코 소개 1부 컨텐츠를 제작한다 - 5월 9일 (업로드: 5월 17일)

### ISSUE THREAD

**Issue by awesomeo184** [woowacourse/Branding#3]

**Comment by byhhh2** [comment]
## 공통 스타일

### 색상 

- 진한 민트색 : `#2AC1BC` -> 포인트 컬러로 쓰세요.
- 연한 민트색 : `#B8E6E1` -> 베이스 민트색
- 검정색, 흰색 
- 폰트 : 배민 한나체 

### 컨셉

- 우주, 행성

**Comment by byhhh2** [comment]
미리캔버스 템플릿 : 노랑색과-검정색의-힙한-테마-설-이벤트-카드뉴스

**Comment by byhhh2** [comment]
- 내일 5월 7일 토요일 밤 12시까지 각자 맡은 파트 하기
- 월요일 회의 30분 전 (2시 30분)

**Comment by byhhh2** [comment]
> - 3명이 내용 채우기 (asset도 넣고, 위치도 슥삭, 컨텐츠 채워놓기) 
> - 1명 검수, 최종 수정  

1. 검수자가 템플릿을 정하고, 3명에게 알린다.
2. 3명이 컨텐츠를 채워놓는다.
3. 검수자가 최종 검수를 하고 통일성있게 수정을 한다. 

1부 -> 검수자 : 마루
2부 -> 검수자 : 무비

**Comment by Wonmi91** [comment]
수고하셨습니다 : )

https://www.instagram.com/p/CdpuZ3UrWzm/?utm_source=ig_web_copy_link
