### ISSUE TITLE
[문화] 3기 인터뷰 1, 2편 최종본과 3, 4편 초안을 제작한다. 

### ISSUE THREAD

**Issue by byhhh2** [woowacourse/Branding#301]

**Comment by chawani** [comment]
완태 - https://www.miricanvas.com/v/11jybsx

**Comment by byhhh2** [comment]
현구막 - https://www.miricanvas.com/v/11jz75e

**Comment by jin7969** [comment]
👍

**Comment by tonic523** [comment]
👍

**Comment by Wonmi91** [comment]
@chawani 완태 인터뷰는 '핵클' 회사 홍보 같은 느낌이 살~짝 들어서, 수정을 좀 하면 좋을 거 같은데요!
1. 취준생 시절 회사 선정 기준
   - 핵클이 말하는 가치를 공감했고~ 시니어 개발자 출신이며 의 내용은 삭제하고 내용을 좀 다듬으면 좋을 거 같아요~ 보편적인 내용으로!
2. 서류 혹은 면접 팁
   - 커피챗 시스템 운영 내용은 좋은데 역시나 핵클을 1순위로 ~ 라는 내용이 조금 걸려서 ㅎㅎ 마지막 부분만 스타트업에 지원하게 될 때 망설여지는 부분들이 커피챗 질문으로 많이 해소될 수 있으니 시도해보면 좋겠다 정도의 내용이면 좋겠네요!

3. 꾸준히 성장할 수 있는 자신만의 방법
   - 아래 AWS re:Invent 참여 특전은 지우시죠 ㅎㅎ

**Comment by chawani** [comment]
검프 - https://www.miricanvas.com/v/11kotjz

**Comment by byhhh2** [comment]
웨지 - https://www.miricanvas.com/v/11kpd1j

**Comment by jin7969** [comment]
👍

**Comment by byhhh2** [comment]
> 웨지 - https://www.miricanvas.com/v/11kpd1j

글또를 강조한다. (글또 로고라던지, 따옴표 추가)

**Comment by Wonmi91** [comment]
#342 #341 #340 #334
