### ISSUE TITLE
[문화] 레벨5 생활기 최종본을 제작한다.

### ISSUE THREAD

**Issue by jin7969** [woowacourse/Branding#302]

**Comment by jin7969** [comment]
https://www.miricanvas.com/v/11iyh66

사진은 더 첨부할 예정입니다.

**Comment by yeongunheo** [comment]
- 띄어쓰기 수정 (하기 위해)
- 전체적으로 맞춤법검사 돌리기
<img width="904" alt="image" src="https://user-images.githubusercontent.com/52141636/200237381-ce762a1c-1603-4028-81e2-fbf12f032ba1.png">

- 지난간 => 지나간
<img width="666" alt="image" src="https://user-images.githubusercontent.com/52141636/200237498-fe365882-4f92-41dc-b9e1-fcc507bbb00e.png">

**Comment by yeongunheo** [comment]
피드백 모두 수정 완료했습니다!
