### ISSUE TITLE
[문화] 프리코스 커뮤니티 최종본을 제작한다.

### ISSUE THREAD

**Issue by tonic523** [woowacourse/Branding#304]

**Comment by tonic523** [comment]
[미리캔버스 링크](https://www.miricanvas.com/v/11iwcza)

**Comment by jin7969** [comment]
띄어쓰기 해주세요 ㅎ
<img width="691" alt="스크린샷 2022-11-07 오후 2 49 03" src="https://user-images.githubusercontent.com/82227098/200235639-d58a5480-91f5-4076-a582-2136102451f9.png">

**Comment by yeongunheo** [comment]
페이지당 글자수가 너무 많은 것 같아요!
그래서 내용이 한눈에 잘 안들어오는 것 같습니다ㅠ

**Comment by Wonmi91** [comment]
해당 내용 왼손/브라운/네오에게 한번 검수 받아보시는게 좋을 것 같아요.

- 유튜브에 공개된 내용이라 크게 문제는 없을 것 같은데, 해당 깃헙 주소가 공개되어도 되는지 (5기 지원자만 참여 가능한 건 아닌지) 확인!

인터뷰 파트는 '인터뷰' 라고 되어있지만, 누구의 인터뷰인지 알 수가 없어서 인터뷰 대상을 추가해주시면 어떨까요? (왼손, 포비 등)

마지막 장 깃헙 아이디는 가려주셔도 좋을 듯합니다!
