### ISSUE TITLE
[테코톡] 조조그린의 테코톡 최종본을 제작한다

### ISSUE THREAD

**Issue by bcc0830** [woowacourse/Branding#314]

**Comment by bcc0830** [comment]
[편하게 보기](https://www.miricanvas.com/v/11jyu9z)

**Comment by chawani** [comment]
👍

**Comment by tonic523** [comment]
👍

**Comment by jin7969** [comment]
마지막 프로필에서 말풍선을 꼬리를 아래로 하거나, 옆으로 맞추면 좋을거 같아요
<img width="672" alt="스크린샷 2022-11-14 오후 3 08 57" src="https://user-images.githubusercontent.com/82227098/201587693-f5d6c828-4f4a-41e4-8380-a0c604d0de0c.png">
