### ISSUE TITLE
[테코톡] 릭의 테코톡 최종본을 제작한다

### ISSUE THREAD

**Issue by yeongunheo** [woowacourse/Branding#316]

**Comment by yeongunheo** [comment]
https://www.miricanvas.com/v/11jxm5l

**Comment by Gyuchool** [comment]
![image](https://user-images.githubusercontent.com/60054318/201574976-7fc3852a-eab6-43bf-a46c-4a800949b8e3.png)  

디스크로부터 붙이면 좋을 것 같아요!

**Comment by jin7969** [comment]
👍

**Comment by chawani** [comment]
👍
