### ISSUE TITLE
[테코톡] 짱구의 테코톡 최종본을 제작한다.

### ISSUE THREAD

**Issue by Gyuchool** [woowacourse/Branding#318]

**Comment by Gyuchool** [comment]
https://www.miricanvas.com/v/11jvabu

**Comment by yeongunheo** [comment]
`중복 값` 단어를 붙이면 좋을 것 같아요!

<img width="888" alt="image" src="https://user-images.githubusercontent.com/52141636/201577092-4ba52275-8a03-44f2-a6f6-7203b0b5759c.png">

**Comment by jin7969** [comment]
행간을 띄우면 좋을거 같아요
<img width="765" alt="스크린샷 2022-11-14 오후 1 47 05" src="https://user-images.githubusercontent.com/82227098/201577503-80ba28d2-0aaf-4876-8519-d36eb1f7f3e6.png">

**Comment by chawani** [comment]
목차 글씨 조금만 키워도 좋을 것 같아요👍
