### ISSUE TITLE
[테코톡] 콤피의 테코톡 최종본을 제작한다.

### ISSUE THREAD

**Issue by kamwoo** [woowacourse/Branding#319]

**Comment by kamwoo** [comment]
[링크](https://www.miricanvas.com/v/11k0bov)

**Comment by yeongunheo** [comment]
질문에 대한 정답도 한 페이지에 있으면 좋을 것 같아요!

<img width="899" alt="image" src="https://user-images.githubusercontent.com/52141636/201576557-c4cc04f5-4fc8-47cb-aa7d-14c717235a71.png">

**Comment by chawani** [comment]
윗 의견이랑 비슷한데 한페이지 더 만들거나 영상에서 확인해달라는 말을 넣으면 좋을 것 같아요!
