### ISSUE TITLE
[테코톡] 봄의 테코톡 최종본을 제작한다

### ISSUE THREAD

**Issue by yeongunheo** [woowacourse/Branding#324]

**Comment by yeongunheo** [comment]
https://www.miricanvas.com/v/11kpvbc

**Comment by jin7969** [comment]
- 행간을 띄우면 좋을거 같아요
<img width="776" alt="스크린샷 2022-11-21 오후 2 29 04" src="https://user-images.githubusercontent.com/82227098/202972726-5061c120-6849-4e6d-8fd4-229168108b61.png">

- JoinPoint 똑같이 맞추면 어떨까요?
<img width="488" alt="스크린샷 2022-11-21 오후 2 30 15" src="https://user-images.githubusercontent.com/82227098/202972786-2126faf3-23a6-4c3b-9eae-34cbf5073f61.png">

**Comment by chawani** [comment]
마지막장 말풍선 글자 크기를 조금만 줄여도 좋을 것 같아요~

**Comment by tonic523** [comment]
👍

**Comment by yeongunheo** [comment]
피드백 모두 반영했습니다!
