### ISSUE TITLE
[테코톡] 매트, 토르의 테코톡 최종본을 제작한다.

### ISSUE THREAD

**Issue by tonic523** [woowacourse/Branding#325]

**Comment by tonic523** [comment]
- [PR](https://github.com/woowacourse/Branding/pull/331)
- [미리캔버스](https://www.miricanvas.com/v/11kpio6)

**Comment by yeongunheo** [comment]
- `조회 요청이 쓰기 요청보다 압도적으로 많기 때문에 조회 성능을 위해 쓰기 성능을 희생해도 괜찮다!` 라는 의미의 문장이 들어가도 괜찮을 것 같아요!

<img width="600" alt="image" src="https://user-images.githubusercontent.com/52141636/202973876-0123b8b9-befa-4d0b-b65a-39594043f1d0.png">

FRONTEND 꼬재, BACKEND 매트라는 용어보다는 `불필요한 데이터를 skip하고 필요한 데이터만 읽어 디스크 IO를 줄일 수 있다` 라는 식으로 표현하는건 어떨까요? 외부인들이 보기에 꼬재, 매트라는 크루이름은 잘 모를것 같아서요!

<img width="600" alt="image" src="https://user-images.githubusercontent.com/52141636/202974042-8a922b08-b222-469f-9611-9b00ab38719a.png">

`있는` 단어를 줄바꿈 해주면 좋을 것 같아요!

<img width="600" alt="image" src="https://user-images.githubusercontent.com/52141636/202974372-f54c1b98-e58b-4df4-bb17-9a25bc52da32.png">

**Comment by chawani** [comment]
👍
