### ISSUE TITLE
[테코톡] 수달의 테코톡 최종본을 제작한다

### ISSUE THREAD

**Issue by awesomeo184** [woowacourse/Branding#326]

**Comment by awesomeo184** [comment]
https://www.miricanvas.com/v/11kqcp7

**Comment by jin7969** [comment]
- 글씨를 조금 키우면 어떨까요?
<img width="783" alt="스크린샷 2022-11-21 오후 2 33 43" src="https://user-images.githubusercontent.com/82227098/202973098-03005a8a-9f05-4cf4-9c6f-3a5c0bf35856.png">

- 조금 비어 보여서 요소를 추가하거나 이미지 추가하면 어때요?
<img width="688" alt="스크린샷 2022-11-21 오후 2 33 59" src="https://user-images.githubusercontent.com/82227098/202973108-fbde112f-d57f-4b33-abc8-2ccf5dd973b0.png">

**Comment by yeongunheo** [comment]
저도 안의 의견처럼 글씨를 좀 더 키우는게 좋을 것 같아요!

**Comment by tonic523** [comment]
동의합니다!

**Comment by chawani** [comment]
👍

**Comment by yeongunheo** [comment]
`할 수` 이부분 뭔가 띄어쓰기 2번된 것 같아요!

<img width="632" alt="image" src="https://user-images.githubusercontent.com/52141636/202979468-efddc92b-db0b-4ac3-9bba-b0f60cdac672.png">
