### ISSUE TITLE
[영상] 첫번째 영상 컨텐츠를 기획한다.

### ISSUE THREAD

**Issue by Wonmi91** [woowacourse/Branding#348]

**Comment by kong-hana01** [comment]
# 영상 기획 4월 19일

(진행자, 서기: 콩하나)

### 기획 아이템 제안

- vlog / 행사 촬영 → 우테코 메인 외적인 영상
- 크루들의 장비 소개 및 인터뷰
- 코치 인터뷰, 리뷰어 인터뷰 등 기존 포멧
- 캠퍼스 주변 맛집 소개 영상
- 당신의 마지막 쉘 명령어는?
- 무슨 노래 듣고 계세요?
- 웹드라마 느낌

---

### 선호하는 아이템

- 그레이: 첫 영상이니까 오프닝 느낌으로 **캠퍼스 소개나 맛집 소개** 등등 하는 것도 좋을 것 같다.
- 룩소: 기존에 했던 것: 인터뷰해보는 것이 어떨까? → 레퍼런스가 있기 때문

첫 영상이기때문에 기존 레퍼런스를 참고할 수 있는 인터뷰가 적절하다고 판단되어 **인터뷰로 아이템 선정**!

## 인터뷰

### 인터뷰 포멧

- 코건: 크루가 크루에게, 우테코 생활, 데일리조 느낌
- 콩하나: 리뷰어/리뷰이와의 인터뷰, 릴레이 인터뷰

→ 인터뷰 포멧은 **릴레이 인터뷰**로 아이템 선정!

### 릴레이 인터뷰 규칙

1. 질문은 대중들이 들었을 때 충분히 이해할 수 있는 질문을 한다. → 영상 기획팀이 작성
2. 한 인터뷰이에 대한 질문의 개수는 2~3개로 제한한다.
3. 캠퍼스 별로 적절하게 인원수를 배분해 영상을 촬영한다.
4. 촬영 기간은 5월 2일 ~ 4일로, 중간에 캠퍼스를 한번 옮기는 영상을 찍는다.
5. 최대 15명까지 인터뷰이 인원수를 제한한다.

---

### 다음 회의

시간: 4월 27일 목요일 오후 6시 반

장소: 잠실 캠퍼스

내용: 질문 리스트 점검, 인터뷰이 점검, 촬영 도구 체크(개인 폰 사용?),  캠퍼스 옮기는 작업은 영상 기획 팀에서 할지 결정.

### 다음 회의 이전까지 영상기획팀이 해야하는 일

1. 릴레이 인터뷰이 참여자 모집글 업로드 → 슬랙을 통해 공유(코건 담당, 4월 20일 업로드 예정)
2. 질문 리스트 작성 → 대중들이 들었을 때 이해할 수 있는 질문 리스트로 작성

**Comment by Kim0914** [comment]
# 영상 기획 4월 27일

### 촬영방법

* 인터뷰어를 전환할 때 어떻게 할지
    * 사회자 한 명을 섭외해서 영상 마무리까지 유지하는 방법
    * 참가자 모집 완료 후 사회자 신청 받아보기
    * 사회자 없이 자연스럽게 카메라를 전환하는 방법도 생각해보면 좋겠다

* 화면에는 인터뷰어, 인터뷰이 함께 나오게 촬영한다.
    * 자연스럽게 서로 문답하는 방식으로 촬영한다.
    * 참가자들에게 질문은 미리 선별해서 알려준다.

* 영상 오프닝은 어떻게 할지
    * 첫 번째 인터뷰하는 사람이 오프닝과 클로징을 하는 걸로 한다.
    * 신청자 있는 경우, 해당 사람이 하도록 한다.
    * 만약 없는 경우, 영상 근로 크루들 중 한명이 한다.

### 촬영도구
* 삼각대
    * 전 기수에 사용하고 남은 것이 있는지 확인
    * 만약 없다면 자체적으로 구매해서 사용
* 영상 근로 크루 휴대폰으로 촬영


### 질문 리스트
- 인생에서 가장 큰 영감을 준 사람은 누구인가요?
- 1년간 몰입했던 경험 항목으로 어떤 걸 작성하셨나요?
- 우테코가 가진 가장 큰 강점이 무엇이라고 생각하시나요?
- 우테코에서 어떤 것을 배우나요?
- 최근에 한 미션을 소개해주세요.
- 프리코스 시작 전과 비교해서 얼마나 성장했나요? 구체적으로 알려주세요
- 어떤 장비를 쓰고 계시나요?
- 우테코를 지원한 계기가 궁금합니다.
- 백/프론트/안드로이드 중 왜 이 분야를 선택하셨나요?
- 첫 페어 프로그래밍의 경험이 궁금해요.
- 우테코에서의 하루 스케줄이 궁금합니다.
- 전공이 어떻게 되시나요?
- 코딩을 시작한 계기가 궁금합니다.
- 닉네임 선정 이유

**Comment by Kim0914** [comment]
릴레이 인터뷰 촬영 일정

https://docs.google.com/spreadsheets/d/1oCLhQrpeux-C7uEjc6ZCXnPKcfBXus5k0AeJxrRA8CY/edit#gid=0
