### ISSUE TITLE
[테코톡] 테코톡 영상을 제작한다.

### ISSUE THREAD

**Issue by ezzanzzan** [woowacourse/Branding#359]
### 테코톡 공지
- 담당자 : `마코`
- 전체 템플릿
```markdown
@channel
안녕하세요! :교사: 오늘은 테코톡이 있는 날입니다. 테코톡은 매주 목요일 오후 2시에 진행되며, 관심이 있다면 자유롭게 오셔서 들을 수 있어요! :celebration:
채팅을 하고 싶다면 Zoom 채팅의 받는 사람을 ‘모두’로 설정해야 모두가 볼 수 있어요.
QnA를 사용하여 질문을 등록해 주세요. :미소짓는_얼굴:

**[Zoom 링크]**
잠실 캠퍼스: https://woowahan.zoom.us/j/81907818235?pwd=KzdrYTQ4TTViU290U1VkRXVrSStQUT09
선릉 캠퍼스: https://woowahan.zoom.us/j/88902785356?pwd=cHlWZTN2YUJKM3RVUndLSDZTa3JDdz09

**[오늘의 주제 - 발표자]**
- 잠실 캠퍼스
    - 주제 - 크루 이름
- 선릉 캠퍼스
    - 주제 - 크루 이름

:아래를_향한_작은_빨간색_삼각형: 테코톡의 모든 곳
https://docs.google.com/spreadsheets/d/1pHsJYxNfM3fQbJ8fdtHF9ovj9-vGhXLpS-6ZfxiShdU/edit?usp=sharing```
```
- 선릉 방청 신청 템플릿
```markdown
@channel
오후 2시부터 **무중력 광장**에서 테코톡을 진행할 예정입니다.
**[방청 안내]**
공간이 협소하여 한정된 인원만 수용하기 위해 미리 **오프라인 방청 신청**을 받으려고 합니다.
방청 신청은 선착순 **20명**만 받겠습니다. 오프라인에서 테코톡을 직관하거나 발표자를 응원하고 싶은 크루들은 이 글 스레드에 댓글을 남겨주시면 됩니다. 오프라인 방청을 신청하지 못한 크루들은 온라인 Zoom으로 테코톡을 시청할 수 있습니다.
**[발표자 안내]**
오늘 발표 예정인 크루들은 1시 45분까지 무중력 광장에 와서 본인의 기기가 잘 연결되는지 확인해주세요.
```

### 테코톡 진행 메뉴얼 작성하기
- [ ] ~~선릉캠 메뉴얼 작성~~
- [ ] ~~잠실캠 메뉴얼~~
- [x] 공통 메뉴얼

### 썸네일
- 이전 기수 썸네일 그대로 진행

### Vrew 체험
- [x] 화요일 18시까지 스레드에 각자 선택한 자막 템플릿 올리고 투표하기

### 영상 편집
- [x] 제이 : 썬샷
- [x] 주노 : 토리
- [x] 비버 : 마코
- [x] 글로 : 코비
- [x] 가브리엘 : 에이든
- [x] 고니 : 코난

**Comment by ezzanzzan** [comment]
BE 주노 테코톡 드라이브 링크
https://drive.google.com/drive/folders/1C_seHfKlN-4IyInl5FkHXFDjIDpKVgT4

**Comment by jariita** [comment]
FE 고니 테코톡 드라이브 링크
https://drive.google.com/drive/folders/1dMeporZO2MGvNIiuR2wmMxa04BIVU9Fo

**Comment by rhkrwngud445** [comment]
AN 글로 테코톡 드라이브 링크
https://drive.google.com/drive/folders/1TEQZ9-79ritMmoi1oDoWnHwI7FCj-Vwm

**Comment by Ohjintaek** [comment]
BE 제이 테코톡 드라이브 링크
https://drive.google.com/drive/folders/1fVnEoNe1VQoO6zIs367U1KIKUDCfPGN2

**Comment by aak2075** [comment]
BE 비버 테코톡 드라이브 링크
https://drive.google.com/drive/folders/1AuXJgruMcSHW2pilcOmC4pWhmvdBeL8x

**Comment by gyeongza** [comment]
FE 가브리엘 테코톡 드라이브 링크
[https://drive.google.com/drive/folders/1Q1q7qZe5SZkrGtdtlBF4Tasei0xuzW65](https://drive.google.com/drive/folders/1Q1q7qZe5SZkrGtdtlBF4Tasei0xuzW65)

**Comment by Wonmi91** [comment]
5/8 업로드 완료  : )
