### ISSUE TITLE
[테코블] 이미지 사이즈 최적화 카드뉴스를 제작한다.

### ISSUE THREAD

**Issue by Leejin-Yang** [woowacourse/Branding#372]
[2조 카드뉴스 드라이브 링크](https://drive.google.com/drive/folders/1bQuLXct5GG0d3QHP4Y75HTfOTK-vIIZk)

**Comment by Leejin-Yang** [comment]
[카드뉴스 미리보기](https://www.miricanvas.com/v/121l74w)

**Comment by aiaiaiai1** [comment]
[카드뉴스 드라이브 링크](https://drive.google.com/drive/folders/1bQuLXct5GG0d3QHP4Y75HTfOTK-vIIZk)
