### ISSUE TITLE
캠퍼스 소개 1부 잠실편 컨텐츠를 제작한다 - 5월 9일 (업로드: 5월 25일)

### ISSUE THREAD

**Issue by jin7969** [woowacourse/Branding#4]

**Comment by tonic523** [comment]
![image](https://user-images.githubusercontent.com/59171113/167302054-0d41df1a-685f-476e-82e6-b57f5c421517.png)

**Comment by tonic523** [comment]
## 회의 내용
https://docs.google.com/presentation/d/16zUOvWx9Rg4bNB3z5kiceUFNbyIHIickQ7tZogTZwkg/edit#slide=id.g1264f7faef5_4_1
