### ISSUE TITLE
[영상] 두번째 영상 컨텐츠를 제작한다.

### ISSUE THREAD

**Issue by Kim0914** [woowacourse/Branding#403]
## 영상 기획
- 테코톡 발표의 준비과정과 끝나는 순간을 담는다. 
- 발표자와 크루들의 인터뷰 영상을 담는다.

### 영상 흐름
- 나레이션으로 시작(테코톡 발표날의 하루는 어떨까? 느낌)
- 발표 당일날 발표자들의 사전 인터뷰
- 발표자들의 리허설 영상
- 발표자들의 찐 발표 직전 인터뷰
- 발표 영상(아주 짧게 -> 테코톡 영상 홍보)
- 발표 후 인터뷰(발표자, 청중)

### 컷편집 기간
- 6월 5일까지 진행
- 영상 원본과 자막 파일을 따로 저장
- 방학 중 작업 완료

### 최종 편집 완료 기간
- 근로 주간 회의 이후 결정
- 6월 27일 완료

### 썸네일 작업 기간
- 6월 30일까지 마무리 예정(작업 완료)

---

### 영상 수정 요청
- 하마드 인터뷰 영상 음성 크기 조절(작업 완료)

**Comment by Kim0914** [comment]
영상 드라이브 저장소
https://drive.google.com/drive/folders/1MxjI8pBe6BvgHW-110sEotxOpMcP9MgT

**Comment by Wonmi91** [comment]
최종본 : https://drive.google.com/drive/folders/1fjg4_v1FWBEK0inbBX9p85DSevQ3b4Jy
