### ISSUE TITLE
[카드뉴스] 로이 컨텐츠의 카드 뉴스를 제작한다.

### ISSUE THREAD

**Issue by the9kim** [woowacourse/Branding#405]
- (주제) 전송 제어 프로토콜이란?
- (작업 내용)
    - 카드 뉴스 최종본 작성
- (링크) [카드 뉴스 제작본](https://www.miricanvas.com/v/12awt2d)

**Comment by Wonmi91** [comment]
https://github.com/woowacourse/tecoble/pull/769

로이의 글이 더 다듬어지고 마무리 된 후 테코블에 게시되고, 카드뉴스 수정까지 완료되면 업로드 할게요 : )

**Comment by the9kim** [comment]
아 네! 카드 뉴스 수정이 필요하다고 미리 말씀 드렸어야 했는데 죄송해요!

테코블 수정 사항을 카드 뉴스에 반영하고 말씀드리겠습니다!

오늘도 고생 많으셨습니다🙂

2023년 6월 29일 (목) 오후 1:52, 이원미 ***@***.***>님이 작성:

**Comment by Wonmi91** [comment]
완성본 : https://drive.google.com/drive/folders/1gTSGhwadSbpmFsdAleJwVyL7O1hOTvAz
