### ISSUE TITLE
[영상] 세번째 영상 컨텐츠를 기획한다

### ISSUE THREAD

**Issue by kong-hana01** [woowacourse/Branding#428]
### 기획 아이템 선정
- 레벨 3가 시작되었으니 각 팀별 특색, 기획, 기술 스택과 관련된 영상 업로드
- 마지막으로 사용한 명령어는?(요기요 레퍼런스)
    - 백엔드: https://www.youtube.com/watch?v=1ZEQNEzqW2A
    - 프론트엔드: https://www.youtube.com/watch?v=e_ZeGvqddy0
- 크루들에게 물어요~ 우테코 홍보 영상 촬영

### 선정 결과
- 레벨 3 기획, 우테코 홍보는 시기가 적절하지 않아 보류
- 마지막으로 사용한 명령어는 영상 분량이 작게 나올것 같다는 우려
    - 마지막으로 작성한 코드
    - 마지막으로 작성한 문서
    - 마지막으로 제작한 피그마
    - 등으로 인터뷰

### 촬영 기간
- ~~7월 3주차 (7월 10일 ~ 7월 14일)에 촬영 완료 예정~~
- 촬영 완료

### 컷편집 기간
- ~~7월 30일까지 컷편집 완료~~
- ~~코수타 포스터 제작으로 8월 4일까지로 변경~~
- 컷편집 완료

### 최종본
https://drive.google.com/drive/folders/1nyp-eD_bYRCJa1RKUdCt_oE9DDRto7xU

- 영상 최종본 제작 완료
- 영상 썸네일 제작 완료
- 8월 16일 수요일 6시 업로드 예정

**Comment by DYGames** [comment]
### 촬영 현황
- 코건 (3/4)
- 룩소 (4/4)

### 이번주 작업 예정
- 컷편집 완료

**Comment by DYGames** [comment]
### 지난 주 작업 내역
- 컷편집 완료
### 다음주 작업 예정
- 최종 편집 및 썸네일
- 영상 중 하나가 녹음이 문제가 발생 해 재촬영 예정
