### ISSUE TITLE
[영상] 코수타 홍보 이미지를 제작한다.

### ISSUE THREAD

**Issue by Wonmi91** [woowacourse/Branding#461]
## 목적
6기 모집 : 작년과 비슷하게 10월 중
- 작년 10월, 모집 전 "온라인 설명회" 진행
- **올해는 온라인 설명회 전, 가볍게 "코수타" 형식으로 우테코에 대한 홍보 진행 예정**
  - 1차(8/2), (2차), 최종 온라인 설명회

- 외부와 소통하는 컨텐츠이기 때문에, 브랜딩 근로 참여 

**따라서 코수타 홍보가 필요함.**

## 요청 사항

- **1차 코수타 홍보 이미지 제작 및 문구 작성 필요**
  - 커버 이미지
    - 우아한테크코스 코치와의 수다 타임에 초대합니다 (예시)
  - 일자 / 시간 / 장소
    - 8월 2일 수요일, 오후 2시
    - 우아한Tech 유튜브 라이브 스트리밍
  - 참석자
    - 캡틴 포비, 코치 왼손
  - 취지
    - 우아한테크코스에 대해 궁금한 점을 "수다"로 해소하고 소통하는 시간!
  - 가벼운 소통 방송이니 가벼운 마음으로 만나요~! 

- 홍보 채널 : 우테코 인스타그램, 우아한Tech 페이스북 (게시는 워니가 담당)
- 게시 일정 : 7월 26일 혹은 27일

## 추후 계획

- 2차 코수타를 진행하게 된다면, 위와 동일하게 홍보 이미지 제작 필요 (추후 일정이 확정되면 공유)
- 기획팀이 이전에 기획해 온 "크루들에게 물어요~ 우테코 홍보영상" 과 연작이라고 생각하면 어떨까?
  - 1차 코수타 - (2차) - 크루들에게 물어요~ 우테코 홍보영상 게시 - 최종 온라인 설명회 
- 최종 온라인 설명회
  - 기존 온라인 설명회에서 진행했던 “크루 패널 토크” 를 브랜딩 근로에서 준비하면 어떨까?
  - https://www.youtube.com/watch?v=RiL-kPRmMKE&t=3747s 1:00:32 ~

### 홍보 이미지 초안
![image](https://github.com/woowacourse/Branding/assets/73513965/a48f7db9-d02b-4d65-a6b8-e72037117059)

**Comment by Wonmi91** [comment]
[피드벡] 
- 우아한테크코스 코치와 수다타임 << 다 같은 글씨체로 통일하고 대충 멋진 배경을 삽입해주시면 더 좋을것 같습니다 ㅋㅋ
- 일정 : 2023년 8월 2일 수요일 오후 2시 (년도, 요일 추가)
- 우아한Tech 유튜브 라이브
- "여섯번째 만남" 이라는 표현이 조금 모호한 감이 있어서, 명확한 문구로 수정해주시면 좋을 것 같아요.
- 인스타 게시글 설명에 들어갈 홍보 문구도 작성해서 코멘트로 남겨주세요.
  - 위에 제가 남긴 일정/ 참석자 / 수다타임의 취지 등이 잘 드러날 수 있게!

**Comment by Kim0914** [comment]
![우테코-6기-최종](https://github.com/woowacourse/Branding/assets/68818952/aa917834-8e01-4c37-b472-e623fdeb0449)

⭐️ 인스타 홍보 문구 ⭐️

우아한테크코스 예비 6기를 위한 코수타가 진행됩니다 👏

✅ 일정
2023년 8월 2일 수요일 오후 2시

✅ 장소
우아한 Tech Youtube 라이브 스트리밍

✅ 대상
- 우테코 6기에 관심 있는 사람 !
- 우테코 코치와 소통하고 싶은 사람 !
- 우테코에 궁금한 점을 해소하고 싶은 사람 !


8월 2일 수요일 오후 2시
우아한 Tech 유튜브에서 만나요
많은 참여 부탁드립니다 😀

**Comment by Kim0914** [comment]
수정본입니다 !!

![우테코-6기-001 (5)](https://github.com/woowacourse/Branding/assets/68818952/0a4f42a0-9449-46e9-8c7c-34566c94729e)

⭐️ 인스타 홍보 문구 ⭐️

우아한테크코스 예비 6기를 위한 코수타가 진행됩니다 👏

✅ 일정
2023년 8월 2일 수요일 오후 2시

✅ 장소
우아한테크 Youtube 라이브 스트리밍

✅ 대상

- 우테코 6기에 관심 있는 사람 !
- 우테코 코치와 소통하고 싶은 사람 !
- 우테코에 궁금한 점을 해소하고 싶은 사람 !


8월 2일 수요일 오후 2시
우아한 Tech 유튜브에서 만나요
많은 참여 부탁드립니다 😀

**Comment by kong-hana01** [comment]
## 유튜브 썸네일

![우아한테크코스_6기_코수타_썸네일](https://github.com/woowacourse/Branding/assets/79015120/a45f81ea-9a1b-42ee-9e8a-2b0afa70c79d)

### 변경 사항
- 일정, 장소, 대상 문구 제거
    - 유튜브 라이브 스트리밍이어서 해당 문구 제거
    - 썸네일을 보고 들어올 수 있도록 간단한 홍보 문구 추가
