### ISSUE TITLE
개편될 우아한테크코스 공식 홈페이지에 들어갈 영상을 기획 및 촬영한다.

### ISSUE THREAD

**Issue by Wonmi91** [woowacourse/Branding#475]
https://woowacourse.oopy.io/

### 영상 편집
- 기한: 23년 08월 28일(월)
  - 방학도 기한에 포함되어 있기 때문에 방학 이전인 08월 17일까지 최대한 진행
- [레퍼런스](https://s3.ap-northeast-2.amazonaws.com/recruit.madup.com/madup_PageVideo.mp4)를 참고하여 기존 촬영한 영상 소스들을 편집해서 영상을 업로드할 예정
- 해당 영상 편집관련해서 영상 기획 팀원들과 이야기 나눠야함

### 영상 소스
- 릴레이 인터뷰 영상 : 3초
- 테코톡 영상에서 질의 응답 or 발표하는 장면: 3초
- 테코톡로그에서 시작 영상 인사 장면: 2초
- 크루들이 모니터 보고 있는 장면이나 페어로 작업하는 장면 추가 촬영
- 추가 촬영본은 금요일(18일)까지 촬영 예정

**Comment by Wonmi91** [comment]
## 영상 소스

- 릴레이 인터뷰 영상 : 3초
- 테코톡 영상에서 질의 응답 or 발표하는 장면: 3초
- 테코톡로그에서 시작 영상 인사 장면: 2초

각각에서 어떤 부분을 사용할 예정인지 장면 캡쳐 정도 남겨주셔도 좋을 것 같습니다~

**Comment by kong-hana01** [comment]
# 홈페이지에 들어갈 영상

## 영상 예상 소스
### 하늘 + 배민 문구 적힌 영상(3초)
- 영상 사진: 
![image](https://github.com/woowacourse/Branding/assets/79015120/aefe6ee4-a6d8-46f7-b895-0e1a6f3fcdf4)

### 선릉캠퍼스 전경(3초)
- 영상 사진: ![image](https://github.com/woowacourse/Branding/assets/79015120/d5d3a443-893b-4fd0-b383-01eec62cf554)

### 팀 회의(3초)
- 영상 사진: 
![image](https://github.com/woowacourse/Branding/assets/79015120/ee2fad10-a42f-478c-b901-c4700f8e588a)


### 테코톡 로그(3초)
- 영상 사진: 
![image](https://github.com/woowacourse/Branding/assets/79015120/4685c660-618a-481b-a118-d2c2765331ac)


### 마지막으로 작성한 코드(3초)
- 영상 사진: 
![image](https://github.com/woowacourse/Branding/assets/79015120/80408f07-6d66-46ea-9a4d-ec1d0985522f)

**Comment by Kim0914** [comment]
[제작 영상 바로가기](https://drive.google.com/file/d/1-5fUMsdoGSQQ3Rdmb0p-Yk4Tj6FGLBs7/view?usp=drive_link)

**Comment by Kim0914** [comment]
[최종본 링크](https://drive.google.com/file/d/1Bk0twT4cSXCemA9SSiuOGQU35sPQy8A_/view?usp=drive_link)
