### ISSUE TITLE
[테코블] 연어의 글에 대한 피드백을 반영한다.

### ISSUE THREAD

**Issue by hgo641** [woowacourse/Branding#494]
### 이번주 진행 상황
* 연어의 프로필 이미지, 프로필 배경 이미지, 컨텐츠 썸네일 이미지를 제작한다.
* 연어가 작성한 글을 바탕으로 초안을 작성하고, 테코블 레파지토리에 Pull Request를 제출한다.

[테코블 PR 링크](https://github.com/woowacourse/tecoble/pull/783)

### 9/18까지 진행 계획
* [x] 브랜딩 크루(1조 팀원)들의 피드백을 받고 반영한다.

### 9/25까지 진행 계획
* [x] 코치님들의 피드백을 받고 반영한다. (25일 밤까지 반영하고 재리뷰요청 드릴 예정)

**Comment by Wonmi91** [comment]
https://drive.google.com/drive/folders/1a7dRei3ZtzOqGwiIveyr2xfOy0bdeYD3
