### ISSUE TITLE
[영상 기획] 런칭 페스티벌 스케치 영상을 제작한다.

### ISSUE THREAD

**Issue by kong-hana01** [woowacourse/Branding#497]
# 영상 기획 회의
- 일시: 9월 1일(금) 17시
- 장소: 화성 회의실
- 기획 내용
  - `런칭 페스티벌 스케치 영상 제작`으로 결정

**Comment by Kim0914** [comment]
### 우테코 홍보를 목적으로 하는 영상을 제작한다.

* 우테코 전반적인 홍보 영상

* 레벨 3 돌아보기
  * 서비스 소개
  * 팀 문화
  * 자랑하고 싶은 기술
  * 시연 등등..

* 레벨 4 우테코 크루의 하루

**Comment by kong-hana01** [comment]
## 런칭 페스티벌 영상 제작
### 일정
-  `영상 촬영` 단계가 없기에 3주 동안 영상을 제작하기로 결정
  - 1주차: 홈페이지 영상 피드백 반영 / 런칭 페스티벌 영상 구성 논의
  - 2주차: 런칭 페스티벌 컷편집 영상 제작
  - 3주차: 런칭 페스티벌 자막 작업 및 배경음악 추가 등 최종 편집 영상 제작

### 런칭 페스티벌 영상 구성 논의 사항
#### 1. 촬영 영상 중 대부분이 이동하면서 찍은 영상
- 기존 유튜브에 올라온 `데모데이 스케치 영상`은 대게 `팀 별로 인터뷰를 하거나`, `지금 팀이 무슨 작업을 하는지` 등에 내용이 올라와있음
- 현재 촬영된 영상은 주로 `이동하면서 런칭 페스티벌의 분위기를 담은 영상`임
- 따라서 영상 구성을 `팀 별 소개`의 느낌보다는 `런칭 페스티벌 자체`에 초점을 맞추고자 함
  - ex) 오전에는 팀 별로 부스 준비하는 내용, 오후에는 팀 발표, 부스 활동 등 하는 내용을 영상으로 남김

#### 2. 잠실 캠퍼스와 선릉 캠퍼스의 영상 차이
- 잠실 캠퍼스와 선릉 캠퍼스의 영상 개수에 차이가 있음
  - 잠실: 43개
  - 선릉: 8개(그 중 세로 영상 2개 포함)
- `선릉 캠퍼스의 발표 영상을 의도적으로 넣어서` 영상에 나오는 두 캠퍼스의 비율을 맞춰야할 것으로 보임
- `컷편집 영상을 제작한 이후 영상의 흐름을 고려하여 재논의` 예정

**Comment by Wonmi91** [comment]
https://www.youtube.com/watch?v=D8OLeqFDS7M&t=24s
https://youtu.be/qdQRV2U8Y6Y?si=W8rGlGkKA4wWCS91

기획하신것처럼 팀 별 소개보다 **현장 분위기가 어땠는지~ 우리 이런거 했어요~** 를 그려주는 영상으로 편집 해주시면 됩니다 : )

**Comment by kong-hana01** [comment]
최종 영상
- 링크: https://drive.google.com/drive/folders/1UcQR2H3e410UMkKEZ3FCQYlFGDajytKE

**Comment by Kim0914** [comment]
## 썸네일

![론칭페스티벌_썸네일](https://github.com/woowacourse/Branding/assets/68818952/ee836abf-7552-4668-8e23-b6ea7b065fd2)
