### ISSUE TITLE
[테코블] 테오(포이) 글 코치분들 리뷰를 반영후 업로드하고 카드 뉴스를 제작한다.

### ISSUE THREAD

**Issue by poi1649** [woowacourse/Branding#504]
https://www.miricanvas.com/v/12flzo2

[구글 드라이브 링크](https://drive.google.com/drive/folders/167IZT8P0cj81pBB5yQC78Qn7HdVJRnSW?usp=sharing)

**Comment by Wonmi91** [comment]
https://drive.google.com/drive/folders/14yWix8UcZiM2seXjd6pifkjeTLh0mRnP
