### ISSUE TITLE
[테코블] 애쉬 글 카드 뉴스를 제작한다.

### ISSUE THREAD

**Issue by Jaeyoung22** [woowacourse/Branding#522]
### 진행 상황
* [x] 애쉬 글 카드뉴스를 제작한다.
* [ ] 팀 내에서 카드뉴스 피드백을 진행한다.
* [ ] 피드백을 반영한 카드뉴스를 구글 드라이브에 제출한다.ㅌ

**Comment by Wonmi91** [comment]
https://drive.google.com/drive/folders/1Dmi9VtuchJyFBiXZFz5h5ma4ptx1KtRe
