### ISSUE TITLE
[영상 기획] 5번째 영상 컨텐츠를 기획한다.

### ISSUE THREAD

**Issue by Kim0914** [woowacourse/Branding#524]
## 기획 주제

* 우테코 홍보 영상 - 기획 확정
  * 5기 크루들의 생생한 후기 (크루들의 입장에서 서술하는)
  * 어떤걸 배우는지, 하루 일과는 어떻게 되는지
  * 프리코스, 최종 코딩 테스트
  * 레퍼런스: https://www.youtube.com/watch?v=Mni06Gok5nA&t=282s

* 우테코 선배 인터뷰 (피플행복협조?)
  * 우테코를 다니면서 얼마나 성장했는지
  * 지금 어떤 일을 하고 있는지
  * 우테코에서 학습했던 부분이 어떻게 도움되고 있는지

* 우테코 협업 문화(팀 문화 소개)
  * 데일리 미팅은 어떻게 진행하는지?
  * 회의는 어떻게? 의사 결정은 어떻게? 

--- 
##우테코 홍보 영상
디노, 빅스, 우가, 엽토 지원

## 일정
- ~ 22일까지 촬영

**Comment by DYGames** [comment]
위의 기획 3가지 안 중 브랜딩 크루들의 투표로 결정.

![image](https://github.com/woowacourse/Branding/assets/14182640/b16c3cb5-1f44-4bcb-8b31-4f8017f775de)
- 투표 결과 1안이 선정됨

세부 기획
- ~ 10월 6일
촬영
- 10월 9일 ~ 10월 13일
편집
- 10월 16일 ~ 10월 20일

**Comment by DYGames** [comment]
### 영상 내용
- 학습, 생활, 수료 후 목표 등등 인터뷰
### 일정
- 수~목 인터뷰이 모집, 질문 리스트업
- ~~금~월 촬영 진행~~
  - 현재 출연진과 함께 촬영 날짜 논의 중(월)
  - 이번주 촬영 및 편집을 병행할 예정

**Comment by kong-hana01** [comment]
## 질문 리스트 브레인 스토밍
- 레벨 별 느낀점
- 합격 했을 때 소감
- 몰입 경험에 기재한 내용
- 최종 코딩 테스트 후기
- 팀 프로젝트 하면서 기억에 문제와 해결
- 학습하며 가장 어려웠던 내용
- 팀 프로젝트 하면서 파트별 애로사항
- 프리코스 때 미션을 진행하며 집중했던 부분
- (자소서 작성 시 어떤 부분에 집중했는지)
- 최종 코딩테스트 보는 날의 하루 루틴
- 우테코의 장점
- 우테코가 뭐하는 건지
- 프리코스를 시작하기 전에 (자바/자스/코틀린)을 해본적이 있는지
  - 해본적이 없다면 힘들지 않았는지
- 프리코스 미션 중 가장 기억에 남는 미션
- 프리코스를 진행하면서 가장 몰입했던 부분
- 우테코 협업과정은 어떻게 진행되는지
- 우테코를 시작하기 전, 후로 가장 크게 성장했다고 느끼는 점
- 지금 다시 프리코스로 돌아간다면 어떻게 학습을 해볼건지
- 프리코스 잘 보내는 법(어떻게 하면 프리코스에서 많은 것을 얻어갈 수 있을지)
- 최종 코딩 테스트 팁
- 레벨 별로 뭘 배우는지
- 다른 교육기관과의 차이점
- 우테코 수료 후 목표


# 최종 질문 리스트
## 우아한테크코스 크루들의 후기
- 레벨 별 배우고 느낀 점
- 팀 프로젝트 하면서 파트별 애로사항
- 팀 프로젝트 하면서 문제 상황과 그 해결
- 우테코의 장점
- 우테코가 뭐하는 건지
- 우테코 협업 과정
- 우테코를 시작하기 전, 후로 가장 크게 성장했다고 느끼는 점
- 수료 후 목표
## 우아한테크코스 지원 과정 회고
- 프리코스
  - 기억에 남는 미션
  - 가장 몰입했던 부분
  - 잘 보내는 법
  - 지금 다시 프리코스로 돌아간다면 어떻게 학습 할 것인지
- 자소서
  - 몰입 경험에 기재한 내용
  - 어떤 부분에 집중했는지
- 최종 코딩 테스트
  - 하루 루틴
  - 팁
  - 후기

**Comment by kong-hana01** [comment]
최종 영상 업로드(초반에 등장하는 vrew 제거 예정)
- https://drive.google.com/file/d/11lBThgsuOrOAX902Pk7dfOGuq9MgdI6v/view?usp=sharing

영상 제목
(1) 우아한테크코스 5기의 프리코스 생활
(2) 우아한테크코스 크루들의 회고
(3) 프리코스 꿀팁 : 우테코 5기들의 후기?
(4) 5기에게 들어보는 우테코 프리코스 꿀팁!
(5) 우테코 지원자들 99%가 모르는 5기들의 비밀
(6) 6기 프리코스 이대로만 하면 합격
(7) 이거 안보면 우테코 떨어집니다
(8) 이거 보면 우테코 합격 보장
(9) 우테코를 준비하는 사람들에게


일정
- 10월 30일 근로회의에서 나온 피드백 11월 1일(수요일)까지 반영 예정
- 11월 1일까지 썸네일 제작 예정 
  - 제작 이후 슬랙에 공유 예정
- 11월 1일에 영상 업로드 예정

**Comment by Wonmi91** [comment]
우아한테크코스 붙여서 써주세요 ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by kong-hana01** [comment]
앗 ㅋㅋㅋㅋ 감사합니다
