### ISSUE TITLE
[영상 기획] 최종 데모데이 스케치 영상을 제작한다.

### ISSUE THREAD

**Issue by kong-hana01** [woowacourse/Branding#550]
영상 업로드 주소
- https://drive.google.com/drive/folders/1TLydvo5JpA653AqZ7HrMgkz1i5lU_G8x?usp=sharing

영상 편집 예정 일자
- 10월 31일 ~ 11월 5일: 컷 편집
- 11월 6일 ~ 11월 12일: 최종 편집 예정
- 11월 중순: 피드백 반영 이후 업로드 예정

편집 주의 사항
- [x] 외부인이 들어간 내용은 제외하기

**Comment by DYGames** [comment]
컷 편집 완료
영상 길이 05:27
주소 : https://drive.google.com/file/d/1tZpCpMYoYmadWhhZNeSI2aGbwnHYHNwa/view?usp=sharing
