### ISSUE TITLE
[테코블] 무민 카드뉴스 피드백을 반영하고 최종본을 제작한다.

### ISSUE THREAD

**Issue by poi1649** [woowacourse/Branding#556]
https://drive.google.com/drive/folders/1RnX8HPxEz7YJo10Oou4NRhZEY1dcLTq4?usp=sharing

**Comment by Wonmi91** [comment]
https://drive.google.com/drive/folders/1c3Yo6zR7sgkYHa2Jor-pLyoNBz0iu-Yf
