### ISSUE TITLE
[테코블] 리오 카드뉴스를 제작한다.

### ISSUE THREAD

**Issue by hgo641** [woowacourse/Branding#570]
* [x] 카드뉴스 초안 제작(~11/25)
* [x] 팀원 피드백 진행 (11/25 ~ 11/30)
* [x] 구글 드라이브 제출 (11/30)

**Comment by Wonmi91** [comment]
https://drive.google.com/drive/folders/1XQUCFcxab4I6tX9KphRodlKX071GJCY0
